### ISSUE TITLE
Error in VM Allocation

### ISSUE THREAD

**Issue by Demonsthere** [test-kitchen/kitchen-opennebula#17]
Hey, I have tried to use your driver for Kitchen, and use this https://devcenter.megam.io/test_kitchen as a guideline.  
However, when I try to run `kitchen create` I get this error:

`Failed to complete #create action: [[VirtualMachineAllocate] Error allocating a new virtual machine. Parse error: syntax error, unexpected VARIABLE, expecting COMMA or CBRACKET at line 9, columns 765:768] on ubuntu-master-ubuntu`

My kitchen file looks like this: 

```yml
---
driver:
  name: opennebula
  opennebula_endpoint: 'http://my_server.com:2633/RPC2'
  oneauth_file: '.onefile'
  template_name: Ubuntu4Kube

provisioner:
  name: ansible_playbook
  ansible_vault_password_file: '.vault_pass'
  hosts: localhost
  ansible_verbose: false
  require_chef_for_busser: false
  require_ruby_for_busser: true

platforms:      
  - name: ubuntu

verifier:
  ruby_bindir: '/usr/bin'

suites:
  - name: ubuntu_master
    provisioner:
      playbook: kitchen_playbooks/ubuntu_master.yml
    includes:
      - ubuntu
    attributes:

  - name: ubuntu_slave
    provisioner:
      playbook: kitchen_playbooks/ubuntu_slave.yml
    includes:
      - ubuntu
    attributes:

```

Any ideas or suggestion?
